version: '3.8'
services:
  generator:
    build:
      context: ./go-mqtt_synthetic_generator
      dockerfile: Dockerfile
    environment:
      GENERATOR_BROKER_ADDRESS: andromeda.lasdpc.icmc.usp.br:31883
      GENERATOR_TOPIC: farm_id/device_id/testclient1
      GENERATOR_NUM_DEVICES: "5"
      GENERATOR_PUBLISH_TIMEOUT_MS: "1000"
    restart: always
