kafka:
  brokerAddress: 172.100.10.11:9092
  version: "2.1.0"
  consumerGroupID: my-group
  topic: realtime-data
  assignorStrategy: sticky
  offsetOldest: true
  verbose: false
db:
  host: 
  port: 
  dbName: 
  username: 
  password: 
