kafka:
    brokerAddress: 172.100.10.11:9092
    version: "2.1.0"
    consumerGroupID: my-group
    topic: realtime-data
    assignorStrategy: sticky
    offsetOldest: true
    verbose: false
db:
    host: 172.100.10.20
    port: 5432
    user: admin
    password: admin
    sslMode: disable
    dbName: tcc_icmc
    tableName: temperature_moisture
    conns: 25
    queryTimeout: 10s
    batchSize: 500
    batchFlushTimeout: 5s
